### ISSUE TITLE
linux服务器中，玩家登陆未提醒

### ISSUE THREAD

**Issue by SunShineJF** [eagle3236/joinMOTD-plus-plus#1]
自己windows电脑上，启动服务器后，登陆服务器，会显示自己设置的欢迎语，
但是linux系统上，启动服务器后，登陆服务器后，却没有显示。是有什么地方我没弄对吗？需要我提供什么东西？
linux端，已安装前置（pip3 install requests）

**Comment by SunShineJF** [comment]
HTTPSConnectionPool(host='v1.hitokoto.cn', port=443): Max retries exceeded with url: /?encode=text (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efed0a78c18>: Failed to establish a new connection: [Errno 110] Connection timed out',))
服务器提示这个，是因为什么呢？

**Comment by eagle3236** [comment]
似乎是一言服务器连接异常。请关闭一言功能并重试。
